=== ISA-tools/COPO/web/apps/web_copo/schemas/ena/dbmodels/isa_v1/person_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title" : "ISA person schema",
    "description" : "JSON-schema representing a person in the ISA model",
    "type" : "object",
    "properties" : {
        "lastName" : { "type" : "string"},
        "firstName" : { "type" : "string"},
        "midInitials" : { "type" : "string" },
        "email" : { "type" : "string", "format" : "email"},
        "phone" : { "type": "string"},
        "fax" : { "type" : "string" },
        "address" : { "type" : "string" },
        "affiliations" : {
            "type" : "array",
            "items" : {
                 "$ref": "organization_schema.json#"

            }
        },
        "roles" : {
            "type" : "array",
            "items" : {
                "type" : "object",
                "properties" : {
                    "role": { "type": "string" },
                    "ontologyAnnotation" : {
                        "$ref": "ontology_annotation_schema.json#"
                    }
                }
            }
        }
    }
}

=== ISA-tools/COPO/web/apps/web_copo/schemas/copo/dbmodels/person.json
{
  "lastName": "",
  "firstName": "",
  "midInitials": "",
  "email": "",
  "phone": "",
  "fax": "",
  "address": "",
  "affiliations": [
    {
      "name": "",
      "id": ""
    }
  ],
  "roles": [
    {
      "role": "",
      "ontologyAnnotation": {
        "name": "",
        "termSource": "",
        "termAccession": ""
      },
      "id": ""
    }
  ]
}
